### ISSUE TITLE
Error: gekko/methods/ZERO.js:49

### ISSUE THREAD

**Issue by unstephenk** [kuzetsa/gekko#6] opened 2014-08-16 14:44 UTC
This error causes gekko to crash. I am not sure why I cannot get this bot to work. Its becoming very frustrating. Please help!

Ubntunu 14.04 LTS

/var/www/html/gekko/methods/ZERO.js:49
  log.debug('\t', '40th:', windowstats.p40th.toFixed(digits));
                                             ^
TypeError: Cannot call method 'toFixed' of undefined
    at method.log (/var/www/html/gekko/methods/ZERO.js:49:46)
    at bound [as log](/var/www/html/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.tick (/var/www/html/gekko/core/baseTradingMethod.js:110:10)
    at bound [as tick](/var/www/html/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.processCandle (/var/www/html/gekko/plugins/tradingAdvisor.js:42:15)
    at bound (/var/www/html/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at EventEmitter.emit (events.js:117:20)
    at bound [as emit](/var/www/html/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.relayCandle (/var/www/html/gekko/core/marketManager.js:75:8)
    at bound (/var/www/html/gekko/node_modules/lodash/dist/lodash.js:729:21)

**Comment by kuzetsa** [comment] 2014-08-20 00:17
This error implies that the windowstats period is having difficulty due to being unable to sort the data and select a datapoint from at or around the 40th percentile point in the list. The fact that the error occured on this line means that the nearly identical code for 1st, 5th, 10th, 12th~ish, and 25th percentile were fine, but for some reason the 40th didn't execute normally.

Very very strange behavior, I've never seen this problem, and I'm curious what values you selected in your config.js...

As I said for issue #5:

To assist with troubleshooting bad configuration, please post your config.js on http://gist.github.com/ (_obfuscate or ommit your API keys_) and update this issue with a link to the gist.

Sorry I didn't notice the github issues over the weekend -- My bad, I'll pay closer attention now that I know there's open issues.

**Comment by unstephenk** [comment] 2014-08-23 00:00
https://gist.github.com/2cb8a870f5e66cc76752.git
https://gist.github.com/unstephenk/2cb8a870f5e66cc76752

**Comment by kuzetsa** [comment] 2014-08-24 07:38
I saw from issue #5 that you got it working?

**in hindsight though:**

it's probably a bad thing to have the "ZERO" trading method window size set to a smaller value than the Trading Advisor "historySize" value... but I'm not sure if that's what caused the issue or not.

If so, my fault for not setting up config.ZERO with a sane default value which is no larger than the history size (_which itself is a different type of window, as it's the amount of data used to initialize the EMAs for the algorithm to even work_)

**Comment by unstephenk** [comment] 2014-08-24 14:47
Yeah. Issue #5 was fixed.

So what changes do I make to the zero.js file to get this thing running?

**Comment by kuzetsa** [comment] 2014-08-26 06:54
The one I use is exactly the same as the ZERO.js on github.

```
kuzetsa@yurizoku ~ $ md5sum gekko/methods/ZERO.js
993491f0e7fb3785b3fb6fa5dd285bef  gekko/methods/ZERO.js

kuzetsa@yurizoku ~ $ md5sum gekko/methods/indicators/ZERO.js
e43f8029619ef6c2a7fa189667abf0b7  gekko/methods/indicators/ZERO.js
```

^ files are both dated July 16, and they work as-is, as-expected, and those are the ones I use...

https://github.com/kuzetsa/gekko/archive/b4cae1bb9993d8be2eeaeaf965b98c1ae403f96a.zip

^ that's the version of gekko I'm using, including the ZERO.js...

... the thing which is weird is **the default configuration**<br>(_Which apparently was broken. My bad_)

Try changing it like this:

https://gist.github.com/kuzetsa/986b730087600b69cba2/revisions

(_that's the relevant settings from my own config.js, and it works like that for me_)

... Also, I pushed a patch for this to the master branch since it really was a bad default:

https://github.com/kuzetsa/gekko/commit/ad46d8e0cdbc6c1cb0b25f660f6da8f0e08fd249

---

**Please note:**

I don't think the config.js is what's causing issue #6

**Comment by kuzetsa** [comment] 2014-09-03 07:28
### closing issue

already pushed a patch for the default config.js to have a "less greedy" statistics window<br>(_even included a hint comment that it shouldn't be larger than the history size_)

... I was unable to reproduce this bug / issue using a "not poorly written" config.js

**Closed as completed by kuzetsa** 2014-09-03 07:28 UTC

**Comment by unstephenk** [comment] 2014-09-10 17:48
Success! Thank you!
